site_name: Gesso WordPress Theme
repo_url: https://github.com/forumone/gesso-wp
repo_name: forumone/gesso-wp
site_author: Forum One
site_description: A WordPress starter theme.
copyright: 'Copyright &copy; 2016 - 2017 Forum One'

theme:
  name: 'material'
  logo: 'images/f1-logo-icon.svg'
  palette:
    primary: red
    accent: red

# Options
extra:
  social:
    - type: globe
      link: https://forumone.com
    - type: github-alt
      link: https://github.com/forumone
    - type: twitter
      link: https://twitter.com/forumone
    - type: linkedin
      link: https://www.linkedin.com/company/forum-one

markdown_extensions:
  - admonition
  - codehilite:
      linenums: true
  - toc:
      permalink: true

# Page tree
pages:
  - Overview: index.md
  - Getting Started: getting-started.md
  - Helper Functions: helper-functions.md